In [1]:
import numpy as np

m1 = np.array([[1,4,7],[2,5,8],[3,4,5]])
m2 = np.array([[1,4,5],[1,5,2],[5,6,7]])

addition = np.add(m1, m2)
print("Element-wise addition:\n", addition)

subtraction = np.subtract(m1, m2)
print("Element-wise subtraction:\n", subtraction)

result_dot = np.dot(m1,m2)
print("Matrix multiplication (dot product):\n",result_dot)

result_divide = np.divide(m1,m2)
print("Matrix Division:\n",result_divide)

result_mod = np.mod(m1,m2)
print("Module of m1 to m2 is :\n",result_mod)

result_mul = np.multiply(m1, m2)
print( "Element-wise multiplication:\n",result_mul)

Element-wise addition:
 [[ 2  8 12]
 [ 3 10 10]
 [ 8 10 12]]
Element-wise subtraction:
 [[ 0  0  2]
 [ 1  0  6]
 [-2 -2 -2]]
Matrix multiplication (dot product):
 [[40 66 62]
 [47 81 76]
 [32 62 58]]
Matrix Division:
 [[1.         1.         1.4       ]
 [2.         1.         4.        ]
 [0.6        0.66666667 0.71428571]]
Module of m1 to m2 is :
 [[0 0 2]
 [0 0 0]
 [3 4 5]]
Element-wise multiplication:
 [[ 1 16 35]
 [ 2 25 16]
 [15 24 35]]
